<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>DoomLauncher.Gtk</RootNamespace>
    <AssemblyName>DoomLauncher</AssemblyName>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <ApplicationIcon>..\..\DoomLauncher\DoomLauncher.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="GirCore.Adw-1" Version="0.7.0" />
    <PackageReference Include="GirCore.Gtk-4.0" Version="0.7.0" />
    <PackageReference Include="GirCore.GdkPixbuf-2.0" Version="0.7.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DoomLauncher.Core\DoomLauncher.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="..\..\DoomLauncher\DoomLauncher.ico" CopyToOutputDirectory="PreserveNewest" Link="DoomLauncher.ico" />
    <Content Include="..\..\DoomLauncher\Help.pdf" CopyToOutputDirectory="PreserveNewest" Link="Help.pdf" Condition="Exists('..\..\DoomLauncher\Help.pdf')" />
    <Content Include="..\DoomLauncher.Core\DoomLauncher.sqlite" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\DoomLauncher.Core\TileImages\*" CopyToOutputDirectory="PreserveNewest" Link="TileImages\%(Filename)%(Extension)" />
    <Content Include="io.github.doomedlaunchernix.DoomLauncher.desktop" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
